DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
  id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  price decimal(12,2) NOT NULL,
  date_added timestamp NOT NULL DEFAULT now(),
  checked boolean NOT NULL DEFAULT false,
  category grocery NOT NULL
);

